### ISSUE TITLE
Diferent mmol/mgdl

### ISSUE THREAD

**Issue by rafaena** [sulkaharo/nsfitbit#1]
Good morning, thanks for creating this sphere, the problem is when it is in (mgdl) there is no trend arrow or graph, and when it changes to (mmol) if it appears, I also want to ask for the status lines only appear 2  , how can I have more status lines ?, and finally in the section (Graph top BG) I don't know what I have to put.

**Comment by rafaena** [comment]
![15705296043625295079820835806508](https://user-images.githubusercontent.com/10066930/66387837-157f3c80-e9c5-11e9-906c-8087bb0592ea.jpg)
![IMG_20191008_110203](https://user-images.githubusercontent.com/10066930/66387880-32b40b00-e9c5-11e9-9a61-6221723b5f3a.jpg)

**Comment by rafaena** [comment]
![IMG_20191013_175648](https://user-images.githubusercontent.com/10066930/66719958-c9822c80-edf6-11e9-9f61-fd184cdcda27.jpg)
![IMG_20191013_175454](https://user-images.githubusercontent.com/10066930/66719962-d6068500-edf6-11e9-8e38-9452f203ae54.jpg)

**Comment by rafaena** [comment]
Good afternoon the watchfaces is going very well, but when it is in (mgdl) there are no trend arrows, it can tell me how the trend date is activated in the mgdl option.  thank you

**Comment by TwistaTim** [comment]
This should be fixed now

**Comment by rafaena** [comment]
hello Tornado-Tim, you see the trend arrow with mgdl ??  How can I make it look on the watchface?

**Comment by TwistaTim** [comment]
This issue is now fixed in the code, just needs submission to Fitbit for review.

**Comment by rafaena** [comment]
Thank you very much for the information. Tornado-Tim. 
Saludos
