### ISSUE TITLE
Support for Ionic

### ISSUE THREAD

**Issue by EknalpTiel** [sulkaharo/nsfitbit#16]
If it's supporting the Versa, it should also tun at the Ionic.

**Comment by sulkaharo** [comment]
It's on the todo list. Sadly Ionic has different screen proportions, so the layout needs a redesign to run in the Ionic :(

**Comment by sulkaharo** [comment]
Oops forgot to close this - the watchface has supported Ionic for some time, and I just pushed out a release that improves the layout quite a lot.
