### ISSUE TITLE
Adjustments 

### ISSUE THREAD

**Issue by brandybiggar** [sulkaharo/nsfitbit#20]
Hello,
Your watch face is great! I was just wondering if you could make it so heart rate and steps can go on line 1 and line 2 instead of iob.. where they are now overlaps with the other text
![0A3BB0D5-5342-4CB6-9CFF-D8F2474F1719](https://user-images.githubusercontent.com/44644662/75293942-d29df400-5801-11ea-88bd-9775acfddffd.jpeg)

**Comment by sulkaharo** [comment]
Hi! I just pushed a new layout to the watchface that improves it quite a lot, you might want to take a look if you haven't done so yet.
