### ISSUE TITLE
No issue since the last update of fitbit app 2 days ago.

### ISSUE THREAD

**Issue by Cheun1** [sulkaharo/nsfitbit#55]
Hello ,  since the last update of fitbit app ,Nightscout Monitor do not work , i have check all parameters .
Thank you if you can resolve .
Version of NS Monitor 1.6.1.
Type of watch Fitbit Sense .
Version of fitbit app 3.6.0.
NS 14.2.5
Version firmware Sense VERSION 44.128.6.12.

thank for all.

**Comment by sulkaharo** [comment]
My app only updated just now and the updates broke for me as well. Checking!

**Comment by sulkaharo** [comment]
Right, looks like the new Fitbit application has broken the backward compatibility with apps compiled with an earlier SDK. I have submitted a new build to Fitbit for review, hope they release is quickly.

**Comment by Cheun1** [comment]
Thank you for all

**Comment by sulkaharo** [comment]
The update for the watch face is now live in the Fitbit store. Please update to 1.6.4 and you should be up and running again.

**Comment by Cheun1** [comment]
All is ok now
Thank you✅

Envoyé de mon iPhone
