### ISSUE TITLE
COB isn't rounded to a set number of decimal places

### ISSUE THREAD

**Issue by hamishnorton** [sulkaharo/nsfitbit#6]
Just installed the watch face on my Versa 2, and I'm loving it.
However the COB is reading...
`5.17342777777778`
...perhaps this could be rounded to 1 decimal place.

**Comment by sulkaharo** [comment]
Oh wow! :D Where does your COB data come from? OpenAPS rounds it, so the code currently assumes the number is an int.

**Comment by hamishnorton** [comment]
So just my night scout site, as I'm not an OpenAPS user "yet".

**Comment by sulkaharo** [comment]
Looking at submitting a release, so will be fixed in the Fitbit store version soon (or install using the command line tools to get the fix immediately)

**Comment by hamishnorton** [comment]
Thank you. That's great.

**Comment by sulkaharo** [comment]
5 minutes from report to fix is ok, right? :D
